# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Legal Tools Data
# All technologies used
technologies: Gettext, HTML, RDF
# Whether this repository should be featured on the CC Open Source site
featured: false
# Slack channel name
slack: "cc-dev-legal-tools"
