# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Licenses Data
# All technologies used
technologies: HTML
# Whether this repository should be featured on the CC Open Source site
featured: false
